[package]
name = "empitsu-core-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.84"
core = { path = "../core" }

[features]
default = []
console_error_panic_hook = []
wee_alloc = []