use crate::analysis::break_info::BreakInfo;
use crate::analysis::expression_info::ExpressionInfo;
use crate::analysis::identifier_info::IdentifierInfo;
use crate::analysis::node_info::NodeInfo;
use crate::analysis::type_::Type;
use crate::analysis::type_expression_info::TypeExpressionInfo;
use crate::analysis::variable_info::VariableInfo;
use crate::analysis::Analysis;
use crate::ast::assignment_expression::AssignmentExpression;
use crate::ast::binary_expression::BinaryExpression;
use crate::ast::block::Block;
use crate::ast::bool_literal::BoolLiteral;
use crate::ast::break_::Break;
use crate::ast::call_expression::CallExpression;
use crate::ast::for_statement::ForStatement;
use crate::ast::function::Function;
use crate::ast::get_range::GetRange;
use crate::ast::identifier::Identifier;
use crate::ast::if_expression::IfExpression;
use crate::ast::if_statement::IfStatement;
use crate::ast::impl_statement::ImplStatement;
use crate::ast::interface_declaration::InterfaceDeclaration;
use crate::ast::member_expression::MemberExpression;
use crate::ast::node::Node;
use crate::ast::number_literal::NumberLiteral;
use crate::ast::program::Program;
use crate::ast::return_::Return;
use crate::ast::string_literal::StringLiteral;
use crate::ast::struct_declaration::StructDeclaration;
use crate::ast::type_expression::TypeExpression;
use crate::ast::unary_expression::UnaryExpression;
use crate::ast::variable_declaration::VariableDeclaration;
use crate::error::Error;
use crate::parser::parse;
use crate::position::Position;
use crate::punctuation_kind::PunctuationKind;
use std::collections::{HashMap, HashSet};
use std::ops::{Deref, Range};

struct Env {
    /// Scope position if this env is generated by a scope
    scope: Option<Range<Position>>,

    // Variable
    variables_defined: HashSet<Range<Position>>,
    variables_defined_at: HashMap<String, Range<Position>>,
    variables_initialized_at: HashMap<Range<Position>, Range<Position>>,
    variable_types: HashMap<Range<Position>, Type>,

    /// Variables that are not accessible from the current scope.
    inaccessible_variables: HashMap<Range<Position>, VariableInfo>,

    // Node-level information
    breaks: HashMap<Range<Position>, BreakInfo>,
    identifiers: HashMap<Range<Position>, IdentifierInfo>,
    expressions: HashMap<Range<Position>, ExpressionInfo>,
    type_expressions: HashMap<Range<Position>, TypeExpressionInfo>,

    catch_break: bool,
    exited_by_break: bool,
}

impl Env {
    fn new(
        scope: Option<Range<Position>>,
        catch_break: bool,
    ) -> Self {
        if catch_break && scope.is_none() {
            panic!("Env with catch_break must have a scope");
        }
        Env {
            scope,
            variables_defined: HashSet::new(),
            variables_defined_at: HashMap::new(),
            variables_initialized_at: HashMap::new(),
            variable_types: HashMap::new(),
            inaccessible_variables: HashMap::new(),
            breaks: HashMap::new(),
            identifiers: HashMap::new(),
            expressions: HashMap::new(),
            type_expressions: HashMap::new(),
            catch_break,
            exited_by_break: false,
        }
    }

    fn merge(&mut self, mut child_env: Env) {
        if child_env.scope.is_some() {
            child_env.encapsulate();
        }

        self.variables_defined.extend(child_env.variables_defined);
        self.variables_defined_at.extend(child_env.variables_defined_at);
        self.variables_initialized_at.extend(child_env.variables_initialized_at);
        self.variable_types.extend(child_env.variable_types);

        self.breaks.extend(child_env.breaks);
        self.identifiers.extend(child_env.identifiers);
        self.expressions.extend(child_env.expressions);
        self.type_expressions.extend(child_env.type_expressions);
        self.inaccessible_variables.extend(child_env.inaccessible_variables);
        self.exited_by_break |= child_env.exited_by_break;
    }

    /// Encapsulate variables so that they are not accessible from the outer scope.
    fn encapsulate(&mut self) {
        // Copy variables that are going to be inaccessible
        for (name, defined_at) in self.variables_defined_at.iter() {
            let type_ = self.variable_types.get(defined_at).unwrap_or(&Type::Unknown).clone();
            self.inaccessible_variables.insert(defined_at.clone(), VariableInfo::new(
                defined_at.clone(),
                name.clone(),
                type_,
            ));
            self.variable_types.remove(defined_at);
            self.variables_initialized_at.remove(defined_at);
        }

        self.variables_defined.clear();
        self.variables_defined_at.clear();

        if self.catch_break {
            // Break jump is caught by this scope (= this scope is for-loop scope)
            self.exited_by_break = false;
        }
    }

    fn into_tokens(mut self) -> HashMap<Range<Position>, NodeInfo> {
        self.encapsulate();

        let mut tokens = HashMap::new();
        for (range, variable_info) in self.inaccessible_variables {
            tokens.insert(range, NodeInfo::Variable(variable_info));
        }
        for (range, break_info) in self.breaks {
            tokens.insert(range, NodeInfo::Break(break_info));
        }
        for (range, identifier_info) in self.identifiers {
            tokens.insert(range, NodeInfo::Identifier(identifier_info));
        }
        for (range, expression_info) in self.expressions {
            tokens.insert(range, NodeInfo::Expression(expression_info));
        }
        for (range, type_expression_info) in self.type_expressions {
            tokens.insert(range, NodeInfo::TypeExpression(type_expression_info));
        }
        tokens
    }
}

struct Analyzer {
    /// Environment can be forked to analyze conditional branches.
    envs: Vec<Env>,
    errors: Vec<Error>,
}

impl Analyzer {
    pub fn new() -> Analyzer {
        Analyzer {
            envs: vec![Env::new(None, false)],
            errors: vec![],
        }
    }

    pub fn into_analysis(mut self) -> Analysis {
        while self.envs.len() > 1 {
            self.exit_env();
        }
        let env = self.envs.pop().unwrap();

        Analysis::new(env.into_tokens(), self.errors)
    }

    // Main analysis functions

    fn analyze_node(&mut self, node: &Node) {
        match node {
            Node::Program(program) => self.analyze_program(program),
            Node::IfStatement(if_statement) => self.analyze_if_statement(if_statement),
            Node::ForStatement(for_statement) => self.analyze_for_statement(for_statement),
            Node::VariableDeclaration(variable_declaration) => self.analyze_variable_declaration(variable_declaration),
            Node::FunctionDeclaration(function) => self.analyze_function(function),
            Node::StructDeclaration(struct_) => self.analyze_struct_declaration(struct_),
            Node::InterfaceDeclaration(interface) => self.analyze_interface(interface),
            Node::ImplStatement(impl_statement) => self.analyze_impl_statement(impl_statement),
            Node::Return(return_) => self.analyze_return_(return_),
            Node::Break(break_) => self.analyze_break(break_),
            Node::FunctionExpression(function) => self.analyze_function(function),
            Node::IfExpression(if_expression) => self.analyze_if_expression(if_expression),
            Node::Block(block) => self.analyze_block(block),
            Node::AssignmentExpression(assignment_expression) => self.analyze_assignment_expression(assignment_expression),
            Node::BinaryExpression(binary_expression) => self.analyze_binary_expression(binary_expression),
            Node::UnaryExpression(unary_expression) => self.analyze_unary_expression(unary_expression),
            Node::CallExpression(call_expression) => self.analyze_call_expression(call_expression),
            Node::MemberExpression(member_expression) => self.analyze_member_expression(member_expression),
            Node::Identifier(identifier) => self.analyze_identifier(identifier),
            Node::NumberLiteral(number_literal) => self.analyze_number_literal(number_literal),
            Node::BoolLiteral(bool_literal) => self.analyze_bool_literal(bool_literal),
            Node::StringLiteral(string_literal) => self.analyze_string_literal(string_literal),
            Node::TypeExpression(type_expression) => self.analyze_type_expression(type_expression),
        }
    }

    fn analyze_nodes(&mut self, nodes: &[Node]) {
        for node in nodes {
            if self.exited_by_break() {
                self.errors.push(Error::unreachable_code(node.range()));
                break;
            }
            self.analyze_node(node);
        }
    }

    pub fn analyze_program(&mut self, program: &Program) {
        self.enter_env(Env::new(None, false));
        self.current_env_mut().scope = Some(program.range());

        self.analyze_nodes(&program.statements);

        self.exit_env();
    }

    fn analyze_if_statement(&mut self, if_statement: &IfStatement) {
        self.analyze_node(&if_statement.condition);
        let condition_type = self.get_expression_type(&if_statement.condition.range());
        if !self.is_assignable(&condition_type, &Type::Bool) {
            self.errors.push(Error::unexpected_type_in_if_condition(if_statement.condition.range(), &condition_type));
        }

        self.enter_env(Env::new(None, false));
        self.analyze_node(&if_statement.true_branch);
        let true_env = self.exit_env_without_merge();

        self.enter_env(Env::new(None, false));
        if let Some(false_branch) = &if_statement.false_branch {
            self.analyze_node(false_branch.deref());
        }
        let false_env = self.exit_env_without_merge();

        let child_env = self.reconcile_branched_envs(true_env, false_env);
        self.merge_env(child_env);
    }

    fn analyze_for_statement(&mut self, for_statement: &ForStatement) {
        self.enter_env(Env::new(Some(for_statement.range()), true));

        self.define_variable(for_statement.variable.range(), for_statement.variable.name.clone());
        self.set_variable_type(for_statement.variable.range(), Type::Number);
        self.set_variable_initialized(for_statement.variable.range(), for_statement.variable.range());

        // self.analyze_node(&for_statement.iterable); // TODO
        self.analyze_node(&for_statement.body);

        self.exit_env();
    }

    fn analyze_variable_declaration(&mut self, variable_declaration: &VariableDeclaration) {
        if let Some(initializer) = &variable_declaration.initializer {
            self.analyze_node(initializer);
        }

        self.define_variable(variable_declaration.range(), variable_declaration.name.name.clone());
        if let Some(type_expression) = &variable_declaration.type_ {
            self.analyze_type_expression(type_expression);
            let type_ = self.get_type_expression_type(&type_expression.range());
            self.set_variable_type(variable_declaration.range(), type_);
        }
        if let Some(initializer) = &variable_declaration.initializer {
            let initializer_type = self.get_expression_type(&initializer.range());
            let expected_type = self.get_variable_type(&variable_declaration.range());
            self.report_if_not_assignable(&initializer_type, &expected_type, &initializer.range());

            if variable_declaration.type_.is_none() {
                self.set_variable_type(variable_declaration.range(), initializer_type.clone());
            }

            self.set_variable_initialized(variable_declaration.range(), variable_declaration.range());
        }
    }

    fn analyze_function(&mut self, _function: &Function) {
        unimplemented!("Function analysis is not implemented yet");
    }

    fn analyze_struct_declaration(&mut self, _struct_: &StructDeclaration) {
        unimplemented!("Struct analysis is not implemented yet");
    }

    fn analyze_interface(&mut self, _interface: &InterfaceDeclaration) {
        unimplemented!("Interface analysis is not implemented yet");
    }

    fn analyze_impl_statement(&mut self, _impl_statement: &ImplStatement) {
        unimplemented!("Impl analysis is not implemented yet");
    }

    fn analyze_return_(&mut self, _return: &Return) {
        // Check if return value is valid
        // Check if return value type is correct
        // Check if it is inside a function
        unimplemented!("Return analysis is not implemented yet");
    }

    fn analyze_break(&mut self, break_: &Break) {
        match self.get_breakable_env_position() {
            Some(scope_range) => {
                self.current_env_mut().breaks.insert(
                    break_.range(),
                    BreakInfo::new(break_.range(), scope_range),
                );
                self.current_env_mut().exited_by_break = true;
            }
            None => {
                self.errors.push(Error::invalid_syntax(
                    break_.range(),
                    "Break statement is not inside a loop",
                ));
            }
        }
    }

    fn analyze_if_expression(&mut self, if_expression: &IfExpression) {
        self.analyze_node(&if_expression.condition);
        let condition_type = self.get_expression_type(&if_expression.condition.range());
        if !self.is_assignable(&condition_type, &Type::Bool) {
            self.errors.push(Error::unexpected_type_in_if_condition(if_expression.condition.range(), &condition_type));
        }

        self.enter_env(Env::new(None, false));
        self.analyze_node(&if_expression.true_branch);
        let true_branch_type_ = self.get_expression_type(&if_expression.true_branch.range());
        let true_env = self.exit_env_without_merge();

        self.enter_env(Env::new(None, false));
        self.analyze_node(&if_expression.false_branch);
        let false_branch_type_ = self.get_expression_type(&if_expression.false_branch.range());
        let false_env = self.exit_env_without_merge();

        let child_env = self.reconcile_branched_envs(true_env, false_env);
        self.merge_env(child_env);

        if self.is_assignable(
            &false_branch_type_,
            &true_branch_type_,
        ) {
            self.set_expression_type(if_expression.range(), true_branch_type_);
        } else {
            self.errors.push(Error::conditional_if_expression_type(
                if_expression.range(),
                true_branch_type_,
                false_branch_type_,
            ));
            self.set_expression_type(if_expression.range(), Type::Unknown);
        }
    }

    fn analyze_block(&mut self, block: &Block) {
        self.enter_env(Env::new(Some(block.range()), false));
        self.analyze_nodes(&block.nodes);

        let exited_by_break = {
            let env = self.exit_env_without_merge();
            let exited_by_break = env.exited_by_break;
            self.merge_env(env);
            exited_by_break
        };

        let block_type = if exited_by_break {
            Type::Void
        } else {
            block.nodes.last()
                .map(|last_node| self.get_expression_type(&last_node.range()))
                .unwrap_or(Type::Void)
        };
        self.set_expression_type(block.range(), block_type);
    }

    fn analyze_assignment_expression(&mut self, assignment_expression: &AssignmentExpression) {
        self.analyze_node(&assignment_expression.rhs);
        let rhs_type = self.get_expression_type(&assignment_expression.rhs.range());

        match assignment_expression.lhs.deref() {
            Node::Identifier(identifier) => {
                match self.get_variable_definition_position(&identifier.name) {
                    Some(defined_at) => {
                        let defined_at = defined_at.clone();
                        self.set_identifier_info(assignment_expression.lhs.range(), identifier.name.clone(), Some(defined_at.clone()));

                        let lhs_type = self.get_variable_type(&defined_at);
                        self.report_if_not_assignable(&rhs_type, &lhs_type, &assignment_expression.rhs.range());

                        if !self.is_variable_initialized(defined_at.clone()) {
                            self.set_variable_initialized(defined_at.clone(), assignment_expression.range());
                            self.set_variable_type(defined_at.clone(), rhs_type.clone());
                        }
                    }
                    None => {
                        self.errors.push(Error::undefined_symbol(identifier.range(), identifier.name.clone()));
                        self.define_variable(identifier.range(), identifier.name.clone());
                        self.set_variable_initialized(identifier.range(), assignment_expression.range());
                        self.set_variable_type(identifier.range(), rhs_type.clone());
                    }
                }
            }
            _ => {
                self.errors.push(Error::invalid_syntax(
                    assignment_expression.range(),
                    "Left-hand side of an assignment must be a variable",
                ));
            }
        }

        self.set_expression_type(assignment_expression.range(), rhs_type);
    }

    fn analyze_binary_expression(&mut self, binary_expression: &BinaryExpression) {
        self.analyze_node(&binary_expression.lhs);
        self.analyze_node(&binary_expression.rhs);
        let lhs_type = self.get_expression_type(&binary_expression.lhs.range());
        let rhs_type = self.get_expression_type(&binary_expression.rhs.range());
        let (expected_lhs_type, expected_rhs_type, result_type) = match binary_expression.operator {
            PunctuationKind::Plus => (Type::Number, Type::Number, Type::Number),
            PunctuationKind::Minus => (Type::Number, Type::Number, Type::Number),
            PunctuationKind::Asterisk => (Type::Number, Type::Number, Type::Number),
            PunctuationKind::Slash => (Type::Number, Type::Number, Type::Number),
            PunctuationKind::AndAnd => (Type::Bool, Type::Bool, Type::Bool),
            PunctuationKind::VerticalLineVerticalLine => (Type::Bool, Type::Bool, Type::Bool),

            // TODO
            PunctuationKind::EqualEqual => (Type::Number, Type::Number, Type::Bool),
            PunctuationKind::ExclamationEqual => (Type::Number, Type::Number, Type::Bool),

            PunctuationKind::LeftChevron => (Type::Number, Type::Number, Type::Bool),
            PunctuationKind::LeftChevronEqual => (Type::Number, Type::Number, Type::Bool),
            PunctuationKind::RightChevron => (Type::Number, Type::Number, Type::Bool),
            PunctuationKind::RightChevronEqual => (Type::Number, Type::Number, Type::Bool),

            _ => panic!("Unexpected binary operator {:?}", binary_expression.operator),
        };

        self.report_if_not_assignable(&lhs_type, &expected_lhs_type, &binary_expression.lhs.range());
        self.report_if_not_assignable(&rhs_type, &expected_rhs_type, &binary_expression.rhs.range());

        self.set_expression_type(binary_expression.range(), result_type);
    }

    fn analyze_unary_expression(&mut self, unary_expression: &UnaryExpression) {
        self.analyze_node(&unary_expression.operand);
        let operand_type = self.get_expression_type(&unary_expression.operand.range());

        let (expected_operand_type, result_type) = match unary_expression.operator {
            PunctuationKind::Minus => (Type::Number, Type::Number),
            PunctuationKind::Exclamation => (Type::Bool, Type::Bool),
            _ => panic!("Unexpected unary operator {:?}", unary_expression.operator),
        };

        self.report_if_not_assignable(&operand_type, &expected_operand_type, &unary_expression.operand.range());

        self.set_expression_type(unary_expression.range(), result_type);
    }

    fn analyze_call_expression(&mut self, _call_expression: &CallExpression) {
        unimplemented!("Call analysis is not implemented yet");
    }

    fn analyze_member_expression(&mut self, _member_expression: &MemberExpression) {
        unimplemented!("Member analysis is not implemented yet");
    }

    fn analyze_identifier(&mut self, identifier: &Identifier) {
        let defined_at = match self.get_variable_definition_position(&identifier.name) {
            Some(defined_at) => {
                let defined_at = defined_at.clone();
                self.set_identifier_info(identifier.range(), identifier.name.clone(), Some(defined_at.clone()));
                defined_at
            }
            None => {
                self.errors.push(Error::undefined_symbol(identifier.range(), identifier.name.clone()));
                self.define_variable(identifier.range(), identifier.name.clone());
                self.set_variable_type(identifier.range(), Type::Unknown);
                self.set_variable_initialized(identifier.range(), identifier.range());
                identifier.range()
            }
        };

        if !self.is_variable_initialized(defined_at.clone()) {
            self.errors.push(Error::uninitialized_variable(identifier.range(), identifier.name.clone()));
            self.set_variable_type(identifier.range(), Type::Unknown);
            self.set_variable_initialized(identifier.range(), identifier.range());
        }
    }

    fn set_identifier_info(&mut self, range: Range<Position>, name: String, defined_at: Option<Range<Position>>) {
        self.current_env_mut().identifiers.insert(range.clone(), IdentifierInfo::new(range, name, defined_at));
    }

    fn analyze_number_literal(&mut self, number_literal: &NumberLiteral) {
        self.set_expression_type(number_literal.range(), Type::Number);
    }

    fn analyze_bool_literal(&mut self, bool_literal: &BoolLiteral) {
        self.set_expression_type(bool_literal.range(), Type::Bool);
    }

    fn analyze_string_literal(&mut self, string_literal: &StringLiteral) {
        // TODO
        self.set_expression_type(string_literal.range(), Type::Unknown);
    }

    fn analyze_type_expression(&mut self, type_expression: &TypeExpression) {
        let type_ = match type_expression.name.as_str() {
            "number" => Type::Number,
            "bool" => Type::Bool,
            _ => {
                unimplemented!("Type analysis for identifier is not implemented yet");
            }
        };

        self.set_type_expression_type(type_expression.range(), type_);
    }

    // Break

    /// Get the position of the env that can be exited by break expression.
    fn get_breakable_env_position(&self) -> Option<Range<Position>> {
        self.envs.iter().rev()
            .find(|env| env.catch_break)
            .map(|env| env.scope.clone().unwrap())
    }

    /// Check if the current env is exited by break expression.
    fn exited_by_break(&self) -> bool {
        self.current_env().exited_by_break
    }

    // Env

    /// Get the current env
    fn current_env(&self) -> &Env {
        self.envs.last().unwrap()
    }

    /// Get the current env as mutable
    fn current_env_mut(&mut self) -> &mut Env {
        self.envs.last_mut().unwrap()
    }

    /// Enter a new env.
    fn enter_env(&mut self, env: Env) {
        self.envs.push(env);
    }

    /// Exit current env and merge the result to the parent env.
    fn exit_env(&mut self) {
        let env = self.exit_env_without_merge();
        self.merge_env(env);
    }

    /// Exit current env, but do not merge the result to the parent env.
    /// This is useful when you want to emulate branched env like if-statement.
    fn exit_env_without_merge(&mut self) -> Env {
        self.envs.pop().unwrap()
    }

    /// Merge the given env to the parent env.
    fn merge_env(&mut self, env: Env) {
        self.current_env_mut().merge(env)
    }

    /// Reconcile two branched envs.
    fn reconcile_branched_envs(&mut self, mut env1: Env, mut env2: Env) -> Env {
        let mut result = Env::new(None, false);

        // States inaccessible from outer scope are not needed to be reconciled
        env1.encapsulate();
        env2.encapsulate();

        // Variables defined in the outer scope must be initialized to the same type in both branches
        for (defined_at, env1_initialized_at) in env1.variables_initialized_at.iter() {
            match env2.variables_initialized_at.get(defined_at) {
                Some(env2_initialized_at) => {
                    let env1_type = env1.variable_types.get(defined_at).unwrap_or(&Type::Unknown).clone();
                    let env2_type = env2.variable_types.get(defined_at).unwrap_or(&Type::Unknown).clone();

                    let type_ = if self.is_assignable(&env2_type, &env1_type) {
                        env1_type
                    } else {
                        self.errors.push(Error::conditionally_initialized_as_different_type(env2_initialized_at.clone(), env1_type, env2_type));
                        Type::Unknown
                    };

                    result.variables_initialized_at.insert(defined_at.clone(), env1_initialized_at.clone());
                    result.variable_types.insert(defined_at.clone(), type_);
                }
                None => {
                    self.errors.push(Error::conditionally_initialized_variable(env1_initialized_at.clone()));

                    let type_ = env1.variable_types.get(defined_at).unwrap_or(&Type::Unknown).clone();
                    result.variables_initialized_at.insert(defined_at.clone(), env1_initialized_at.clone());
                    result.variable_types.insert(defined_at.clone(), type_);
                }
            }
        }
        for (defined_at, env2_initialized_at) in env2.variables_initialized_at.iter() {
            if !env1.variables_initialized_at.contains_key(defined_at) {
                self.errors.push(Error::conditionally_initialized_variable(env2_initialized_at.clone()));

                let type_ = env2.variable_types.get(defined_at).unwrap_or(&Type::Unknown).clone();
                result.variables_initialized_at.insert(defined_at.clone(), env2_initialized_at.clone());
                result.variable_types.insert(defined_at.clone(), type_);
            }
        }
        env1.variables_initialized_at.clear();
        env1.variable_types.clear();
        env2.variables_initialized_at.clear();
        env2.variable_types.clear();

        result.merge(env1);
        result.merge(env2);
        result
    }

    // Variable

    fn define_variable(&mut self, range: Range<Position>, name: String) {
        self.current_env_mut().variables_defined_at.insert(name, range);
    }

    fn get_variable_definition_position(&self, name: &str) -> Option<&Range<Position>> {
        for env in self.envs.iter().rev() {
            if let Some(defined_at) = env.variables_defined_at.get(name) {
                return Some(defined_at);
            }
        }
        None
    }

    fn is_variable_defined(&self, name: &str) -> bool {
        self.get_variable_definition_position(name).is_some()
    }

    fn set_variable_type(&mut self, defined_at: Range<Position>, type_: Type) {
        self.current_env_mut().variable_types.insert(defined_at, type_);
    }

    fn get_variable_type(&self, defined_at: &Range<Position>) -> Type {
        for env in self.envs.iter().rev() {
            if let Some(type_) = env.variable_types.get(defined_at) {
                return type_.clone();
            }
        }
        Type::Unknown
    }

    fn set_variable_initialized(&mut self, defined_at: Range<Position>, initialized_at: Range<Position>) {
        self.current_env_mut().variables_initialized_at.insert(defined_at, initialized_at);
    }

    fn is_variable_initialized(&self, defined_at: Range<Position>) -> bool {
        for env in self.envs.iter().rev() {
            if env.variables_initialized_at.contains_key(&defined_at) {
                return true;
            }

            // If the variable is defined in the current scope, but not initialized,
            if env.variables_defined.contains(&defined_at) {
                return false;
            }
        }
        false
    }

    // Expression

    /// Set the type of the expression.
    fn set_expression_type(&mut self, range: Range<Position>, type_: Type) {
        self.current_env_mut().expressions.insert(
            range.clone(),
            ExpressionInfo::new(
                range,
                type_,
            ),
        );
    }

    /// Get the type of the expression.
    fn get_expression_type(&self, range: &Range<Position>) -> Type {
        for env in self.envs.iter().rev() {
            if let Some(info) = env.expressions.get(range) {
                return info.type_.clone();
            }
            if let Some(info) = env.identifiers.get(range) {
                return match info.defined_at {
                    Some(ref defined_at) => self.get_variable_type(defined_at),
                    None => Type::Unknown,
                };
            }
        }
        Type::Unknown
    }

    // Type Expression

    /// Set the type of the type expression.
    fn set_type_expression_type(&mut self, range: Range<Position>, type_: Type) {
        self.current_env_mut().type_expressions.insert(
            range.clone(),
            TypeExpressionInfo::new(
                range,
                type_,
            ),
        );
    }

    /// Get the type of the type expression.
    fn get_type_expression_type(&self, range: &Range<Position>) -> Type {
        for env in self.envs.iter().rev() {
            if let Some(info) = env.type_expressions.get(range) {
                return info.type_.clone();
            }
        }
        Type::Unknown
    }

    fn is_assignable(&self, actual: &Type, expected: &Type) -> bool {
        match (actual, expected) {
            // Never values cannot be assigned to any type
            // since they shouldn't be used as values.
            (Type::Never, _) => false,
            (_, Type::Never) => false,

            // Unknown type is collection of all possible types.
            // It can be assigned only to itself, but can accept
            // any type.
            (Type::Unknown, Type::Unknown) => true,
            (Type::Unknown, _) => false,
            (_, Type::Unknown) => true,

            // Normal type checking
            (Type::Number, Type::Number) => true,
            (Type::Bool, Type::Bool) => true,
            _ => false,
        }
    }

    fn report_if_not_assignable(&mut self, actual: &Type, expected: &Type, range: &Range<Position>) -> bool {
        if !self.is_assignable(actual, expected) {
            self.errors.push(Error::unexpected_type(range.clone(), expected, actual));
            false
        } else {
            true
        }
    }
}

pub fn analyze_program(program: &Program) -> Analysis {
    let mut analyzer = Analyzer::new();
    analyzer.analyze_program(program);

    analyzer.into_analysis()
}

pub fn analyze(source: &str) -> Analysis {
    let parse_result = parse(source);
    if !parse_result.errors.is_empty() {
        for error in parse_result.errors {
            eprintln!("{:?}", error);
        }
        panic!("Failed to parse");
    }

    analyze_program(&parse_result.program)
}

#[cfg(test)]
mod test {
    use crate::analyzer::{analyze_program, Analysis};
    use crate::error::Error;
    use crate::parser::parse;

    mod use_undefined_variable {
        use crate::analyzer::test::{test, AssertMethods};
        use crate::error::Error;
        use crate::position::pos;

        #[test]
        fn use_undefined_variable() {
            test(r#"let x = y"#).assert_errors(vec![
                Error::undefined_symbol(pos(0, 8)..pos(0, 9), "y")
            ])
        }
    }

    mod use_uninitialized_variable {
        use crate::analyzer::test::{test, AssertMethods};
        use crate::error::Error;
        use crate::position::pos;

        #[test]
        fn use_uninitialized_variable() {
            test(r#"let x:number; let y = x"#).assert_errors(vec![
                Error::uninitialized_variable(pos(0, 22)..pos(0, 23), "x")
            ])
        }
    }

    mod type_analyze_in_initialization {
        use crate::analyzer::test::{test, AssertMethods};
        use crate::analyzer::Type;
        use crate::error::Error;
        use crate::position::pos;

        #[test]
        fn correct_type() {
            test(r#"let x:number = 2"#).assert_errors(vec![])
        }

        #[test]
        fn invalid_type() {
            test(r#"let x:number = false"#).assert_errors(vec![
                Error::unexpected_type(pos(0, 15)..pos(0, 20), &Type::Number, &Type::Bool)
            ])
        }
    }

    mod type_analyze_in_assignment {
        use crate::analyzer::test::{test, AssertMethods};
        use crate::analyzer::Type;
        use crate::error::Error;
        use crate::position::pos;

        #[test]
        fn correct_type() {
            test(r#"let x:number = 2; x = 3"#).assert_errors(vec![])
        }

        #[test]
        fn invalid_type() {
            test(r#"let x:number = 2; x = false"#).assert_errors(vec![
                Error::unexpected_type(pos(0, 22)..pos(0, 27), &Type::Number, &Type::Bool)
            ])
        }
    }

    mod type_analyze_in_binary_expression {
        use crate::analyzer::test::{test, AssertMethods};
        use crate::analyzer::Type;
        use crate::error::Error;
        use crate::position::pos;

        #[test]
        fn correct_type() {
            test(r#"1 + 2"#).assert_errors(vec![])
        }

        #[test]
        fn invalid_type_in_rhs() {
            test(r#"1 + false"#).assert_errors(vec![
                Error::unexpected_type(pos(0, 4)..pos(0, 9), &Type::Number, &Type::Bool)
            ])
        }

        #[test]
        fn invalid_type_in_lhs() {
            test(r#"true + 1"#).assert_errors(vec![
                Error::unexpected_type(pos(0, 0)..pos(0, 4), &Type::Number, &Type::Bool)
            ])
        }

        #[test]
        fn invalid_type_in_both() {
            test(r#"true + false"#).assert_errors(vec![
                Error::unexpected_type(pos(0, 0)..pos(0, 4), &Type::Number, &Type::Bool),
                Error::unexpected_type(pos(0, 7)..pos(0, 12), &Type::Number, &Type::Bool)
            ])
        }
    }

    mod type_analyze_in_unary_expression {
        use crate::analyzer::test::{test, AssertMethods};
        use crate::analyzer::Type;
        use crate::error::Error;
        use crate::position::pos;

        #[test]
        fn correct_type() {
            test(r#"!true"#).assert_errors(vec![])
        }

        #[test]
        fn invalid_type() {
            test(r#"!1"#).assert_errors(vec![
                Error::unexpected_type(pos(0, 1)..pos(0, 2), &Type::Bool, &Type::Number)
            ])
        }
    }

    mod type_analyze_for_loop_variable {
        use crate::analyzer::test::{test, AssertMethods};
        use crate::analyzer::Type;
        use crate::error::Error;
        use crate::position::pos;

        #[test]
        fn correct_type() {
            test(r#"
            let x = 1;
            for (i in iterable) {
                x = i
            }
            "#).assert_errors(vec![])
        }

        #[test]
        fn invalid_type() {
            test(r#"
            let x = true;
            for (i in iterable) {
                x = i
            }"#).assert_errors(vec![
                Error::unexpected_type(pos(3, 20)..pos(3, 21), &Type::Bool, &Type::Number)
            ])
        }
    }

    mod unreachable_code_due_to_break {
        use crate::analyzer::test::{test, AssertMethods};
        use crate::error::Error;
        use crate::position::pos;

        #[test]
        fn unreachable_code_in_block() {
            test(r#"for (i in iterable) {
            break;
            let x = 1;
        }"#).assert_errors(vec![
                Error::unreachable_code(pos(2, 12)..pos(2, 21))
            ])
        }

        #[test]
        fn unreachable_code_in_different_block() {
            test(r#"for (i in iterable) {
            {
                break;
                let x = 1;
            }
            let y = 1;
        }"#).assert_errors(vec![
                Error::unreachable_code(pos(3, 16)..pos(3, 25)),
                Error::unreachable_code(pos(5, 12)..pos(5, 21))
            ])
        }

        #[test]
        fn unreachable_code_must_be_reported_only_once() {
            test(r#"for (i in iterable) {
            break;
            let x = 1;
            let y = 1;
        }"#).assert_errors(vec![
                Error::unreachable_code(pos(2, 12)..pos(2, 21))
            ])
        }
    }

    mod conditional_initialization {
        use crate::analysis::type_::Type;
        use crate::analyzer::test::{test, AssertMethods};
        use crate::error::Error;
        use crate::position::pos;

        #[test]
        fn conditional_initialization_true_branch() {
            test(r#"let x
            if (true) { x = 1 }
            x"#).assert_errors(vec![
                Error::conditionally_initialized_variable(pos(1, 24)..pos(1, 29)),
            ])
        }

        #[test]
        fn conditional_initialization_false_branch() {
            test(r#"let x
            if (true) {} else { x = 1 }
            x"#).assert_errors(vec![
                Error::conditionally_initialized_variable(pos(1, 32)..pos(1, 37)),
            ])
        }

        #[test]
        fn full_initialization() {
            test(r#"let x
            if (true) { x = 1 } else { x = 2 }
            x"#).assert_errors(vec![])
        }

        #[test]
        fn nested_conditional_initialization() {
            test(r#"let x
            if (true) {
                if (true) { x = 1 } else { x = 2 }
            } else {
                if (true) { x = 3 }
            }
            x"#).assert_errors(vec![
                Error::conditionally_initialized_variable(pos(4, 28)..pos(4, 33)),
            ])
        }

        #[test]
        fn nested_full_initialization() {
            test(r#"let x
            if (true) {
                if (true) { x = 1 } else { x = 2 }
            } else {
                if (true) { x = 3 } else { x = 4 }
            }
            x"#).assert_errors(vec![])
        }

        #[test]
        fn full_initialization_but_incompatible_type() {
            test(r#"let x
            if (true) { x = 1 } else { x = true }
            x"#).assert_errors(vec![
                Error::conditionally_initialized_as_different_type(pos(1, 39)..pos(1, 47), Type::Number, Type::Bool)
            ])
        }

        #[test]
        fn nested_full_initialization_but_incompatible_type() {
            test(r#"let x
            if (true) {
                if (true) { x = true } else { x = 2 }
            } else {
                if (true) { x = 3 } else { x = true }
            }
            x"#).assert_errors(vec![
                Error::conditionally_initialized_as_different_type(pos(2, 46)..pos(2, 51), Type::Bool, Type::Number),
                Error::conditionally_initialized_as_different_type(pos(4, 43)..pos(4, 51), Type::Number, Type::Bool)
            ])
        }
    }

    trait AssertMethods {
        fn assert_errors(&self, expected: Vec<Error>);
    }

    impl AssertMethods for Analysis {
        fn assert_errors(&self, expected: Vec<Error>) {
            assert_eq!(self.errors, expected);
        }
    }

    fn test(src: &str) -> Analysis {
        let parse_result = parse(src);
        if !parse_result.errors.is_empty() {
            for error in parse_result.errors {
                eprintln!("{:?}", error);
            }
            panic!("Failed to parse");
        }

        analyze_program(&parse_result.program)
    }
}