#[derive(Debug, Clone, PartialEq)]
pub enum PunctuationKind {
    Plus,
    Minus,
    Asterisk,
    Slash,
    LeftParen,
    RightParen,
    LeftBrace,
    RightBrace,
    SemiColon,
    Comma,
    Equal,
    Exclamation,
    AndAnd,
    VerticalLineVerticalLine,
    VerticalLine,
    Dot,
    Colon,
    EqualEqual,
    ExclamationEqual,
    LeftBracket,
    LeftBracketEqual,
    RightBracket,
    RightBracketEqual,
    Question,
}
