#[derive(Debug, Clone, PartialEq)]
pub enum PunctuatorKind {
    Plus,
    Minus,
    Multiply,
    Divide,
    LeftParen,
    RightParen,
    LeftBrace,
    RightBrace,
    SemiColon,
    Comma,
    Assign,
    LogicalNot,
    LogicalAnd,
    LogicalOr,
    Dot,
    Colon,
    Equal,
    NotEqual,
    LessThan,
    LessThanOrEqual,
    GreaterThan,
    GreaterThanOrEqual,
}
